export const DATA_SOURCE = "DATA_SOURCE"
export const USER_REPOSITORY = "USERS_REPOSITORY"
export const NOTIFICATION_REPOSITORY = "NOTIFICATION_REPOSITORY"
export const NOTIFICATIONS_CONTROLLER_PATH = "notifications"
export const AUTH_CONTROLLER_PATH = 'auth'
export const AUTH_REPOSITORY = "NOTIFICATION_REPOSITORY"
export const BOOKINGS_CONTROLLER_PATH = "bookings"